### PR TITLE
Modify bin, geo, stack, window transform typings

### PR DESCRIPTION
**Pull request by invokesus**

### CODE REVIEW

**Comment by invokesus** [comment]
Since `strictNullChecks` is `false`, unioned `Vector2` types are resolving to weird types.
E.g., `[null | number, null | number]` becomes `any[] | number[]` in Vega-Lite.

So, as discussed in slack the types are now less precise, but work with vl.
`Vector2<x| y>`  has been changed to `x[] | y[]` for the transforms with conflicting types.

**Comment by domoritz** [comment]
It's not just less precise but also wrong, imo. 

```
['foo', 2]
```

is type `(number | string)[]` but not `number[] | string[]`

**Comment by invokesus** [comment]
Oops.. I wanted to do `(x|y)[]` instead of `x[]|y[]`.
I'll update the PR.

**Comment by domoritz** [comment]
Can you copy the gist of the slack conversation here so we have it for the future?

**Comment by invokesus** [comment]
>
>Souvik Sen [5:59 PM]
>Suggestions on what the type of `frame`(in `window` and `impute`) should be? (edited)

>Souvik Sen [6:04 PM]
>ideally should be `[null|number, null|number]` but since `strictNullChecks` is false it becomes `any[]| [number |number]`.


>Kanit Wongsuphasawat [10:06 PM]
>How about (number|null)[]. Not the best but more reasonable than that expansion result (which looks like a TS bug unless u have a typo)

**Comment by domoritz** [comment]
Why can't we just add null? I'm confused why this change is necessary. Can you give me examples that should work but don't?

**Comment by invokesus** [comment]
In `src/transform.ts` in vl, [line 189](https://github.com/vega/vega-lite/blob/a41ab180756801b102283f05c7b8bcbaa9215f18/src/transform.ts#L189) if you set frame to be `[null | number, null | number]` which is equivalent to `Vector2<null|number>`, the type resolves to `[number, number]`.

screen shot 2018-07-28 at 6 17 41 pm

**Comment by pelotom** [comment]
>In `src/transform.ts` in vl, [line 189](https://github.com/vega/vega-lite/blob/a41ab180756801b102283f05c7b8bcbaa9215f18/src/transform.ts#L189) if you set frame to be `[null | number, null | number]` which is equivalent to `Vector2<null|number>`, the type resolves to `[number, number]`.

If `strictNullChecks` is disabled, `[number, number]` is the same type as `[null | number, null | number]`, so that all seems correct. Why not just turn on `strictNullChecks` if you want to see the distinction?

**Comment by domoritz** [comment]
We are not ready yet to turn on strict null checks in Vega-Lite but then `[number, number]` is the same as `[null | number, null | number]` so the current typings are fine, I think.

**Comment by invokesus** [comment]
`[null, 0]` is a valid value for `frame`, but because the type is `[number, number]` https://github.com/vega/vega-lite/pull/4073 is failing.

**Comment by pelotom** [comment]
>`[null, 0]` is a valid value for `frame`, but because the type is `[number, number]` https://github.com/vega/vega-lite/pull/4073 is failing.

@invokesus Looking at the log, I can't see anything related to `[null, 0]` not being assignable to `[number, number]`. And on its face I don't understand how that _could_ be a problem if `strictNullChecks` is not enabled.

**Comment by invokesus** [comment]
`[null, null]` is actually the value causing problems.
E.g., there's a line where `frame` is given a default of `[null, null]` which causes this error.
```
src/compile/data/impute.ts:63:58 - error TS7031: Binding element 'frame' implicitly has an 'any[] | [number, number]' type.
63     const {impute, key, keyvals, method, groupby, value, frame = [null, null]} = this.transform;
```

**Comment by domoritz** [comment]
```
interface A {
  a?: [number | null, number | null];
}

const b: A = {a: [0, null]};
const {a = ([null, null] as [null, null])} = b;
```

**Pull request closed without merging**
