### PR TITLE
Fix type of toCanvas()

### PR DESCRIPTION
**Pull request by pelotom**

### CODE REVIEW

**Comment by domoritz** [comment]
Thanks. If you make a release, please remember to make a patch release only.

**Comment by pelotom** [comment]
>Thanks. If you make a release, please remember to make a patch release only.

I'm confused because the version in `package.json` on `master` is `0.3.5`, but `0.3.6` is the latest on NPM?

**Comment by domoritz** [comment]
@kanitw @invokesus Did you publish a version without using Travis? Can you push?

**Comment by invokesus** [comment]
Wasn't me.

**Pull request merged**
