### PR TITLE
add props to SceneLine, remove SceneCube

### PR DESCRIPTION
**Pull request by danmarshall**

### CODE REVIEW

**Comment by domoritz** [comment]
Can you add some tests for this?

**Comment by danmarshall** [comment]
It seems that we would need to stub out a Renderer, since these are used when traversing the scenegraph.

**Comment by domoritz** [comment]
I was imagining that you could generate some scenegraph from a Vega spec and then check it against the types.

**Comment by danmarshall** [comment]
Might be possible, but I do know that Vega scenegraphs aren't exactly serialization-friendly - they have many circular references.

**Comment by domoritz** [comment]
I see. Let's do this in a separate PR then if it's straight forward.

**Pull request merged**
